## Recognizing fraudulent credit card transactions

The dataset contains transactions made by credit cards in September 2013 by european cardholders.
It contains only numerical input variables which are the result of a PCA transformation, to maintain confidentiality. 

The feature 'Class' takes the value 1 in case of a fraud transaction.

The model trained below detects fraud transactions and prevents misuse of credit cards.

In [0]:
import pandas as pd 
import numpy as np

In [0]:
card = pd.read_csv('creditcard.csv')

In [52]:
card.shape

(55551, 31)

In [53]:
card.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [0]:
card = card.dropna()

In [72]:
card.head()

Time        V1        V2        V3  ...       V27       V28  Amount  Class
0     0 -1.359807 -0.072781  2.536347  ...  0.133558 -0.021053  149.62    0.0
1     0  1.191857  0.266151  0.166480  ... -0.008983  0.014724    2.69    0.0
2     1 -1.358354 -1.340163  1.773209  ... -0.055353 -0.059752  378.66    0.0
3     1 -0.966272 -0.185226  1.792993  ...  0.062723  0.061458  123.50    0.0
4     2 -1.158233  0.877737  1.548718  ...  0.219422  0.215153   69.99    0.0

[5 rows x 31 columns]

In [56]:
card.shape

(55550, 31)

In [0]:
x = card.iloc[:, 1:-2]

In [58]:
x.head()

V1        V2        V3  ...       V26       V27       V28
0 -1.359807 -0.072781  2.536347  ... -0.189115  0.133558 -0.021053
1  1.191857  0.266151  0.166480  ...  0.125895 -0.008983  0.014724
2 -1.358354 -1.340163  1.773209  ... -0.139097 -0.055353 -0.059752
3 -0.966272 -0.185226  1.792993  ... -0.221929  0.062723  0.061458
4 -1.158233  0.877737  1.548718  ...  0.502292  0.219422  0.215153

[5 rows x 28 columns]

In [0]:
y = card['Class']



In [60]:
y.head()

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: Class, dtype: float64

In [0]:
y = y.astype(int)

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state = 7, test_size = 0.20)

In [0]:
from xgboost import XGBClassifier

In [0]:
model = XGBClassifier()

In [66]:
model.fit(x_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [0]:
predict = model.predict(x_test)

In [0]:
from sklearn.metrics import accuracy_score, confusion_matrix, precision_recall_curve

In [69]:
accuracy_score(y_test, predict)

0.9997299729972997

In [70]:
confusion_matrix(y_test, predict)

array([[11077,     0],
       [    3,    30]])

In [74]:
precision_recall_curve(y_test, predict)

(array([0.0029703, 1.       , 1.       ]),
 array([1.        , 0.90909091, 0.        ]),
 array([0, 1]))